version: '3.8'

services:
  db:
    container_name: my-postgres-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "5532:5432"  # PostgreSQL exposed to host as port 5532
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8180:8080  # Adminer exposed on host:8180
      - 80:8080  # Adminer exposed on port 80 for Coolify

  pgadmin:
    container_name: my-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com   # Default login email
      PGADMIN_DEFAULT_PASSWORD: admin          # Default login password
    ports:
      - 8081:80  # pgAdmin exposed to host:8081
      - 80:80  # pgAdmin exposed on port 80 for Coolify
    depends_on:
      - db

volumes:
  pgdata:
